# Generated by Django 4.1.3 on 2022-11-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_client_alter_contract_payment_due'),
        ('clients', '0001_initial'),
        ('events', '0003_alter_event_supportcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract'),
        ),
    ]
