# Generated by Django 4.1.3 on 2022-11-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEvents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('payment_due', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_label', models.CharField(max_length=18)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='client',
            name='qualification',
            field=models.CharField(choices=[('PROSPECT', 'PROSPECT'), ('CLIENT', 'CLIENT')], default='PROSPECT', max_length=10),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendees', models.IntegerField(default=1)),
                ('event_date', models.DateTimeField(blank=True)),
                ('notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appEvents.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appEvents.contract')),
                ('event_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='appEvents.status')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='appEvents.client'),
        ),
    ]
