# Generated by Django 4.1.3 on 2022-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvents', '0002_alter_client_company_name_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
    ]
