# Generated by Django 4.1.3 on 2022-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('SALES', 'SALES'), ('SUPPORT', 'SUPPORT'), ('MANAGEMENT', 'MANAGEMENT')], default='MANAGEMENT', max_length=10),
        ),
    ]
