# Generated by Django 4.1.3 on 2022-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('SALES', 'SALES'), ('SUPPORT', 'SUPPORT'), ('MANAGEMENT', 'MANAGEMENT'), ('CONSULT', 'CONSULT')], default='CONSULT', max_length=10),
        ),
    ]
