# Generated by Django 4.1.3 on 2022-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('SALES', 'SALES'), ('SUPPORT', 'SUPPORT'), ('MANAGEMENT', 'MANAGEMENT')], max_length=10),
        ),
    ]
